[package]
name = "pa"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1.12.3"
serde = "1.0.151"
serde_json = "1.0.89"
lz4 = { version = "1.23.1" }
zstd = { version = "0.11" }
arrow = { package = "arrow2", git = "https://github.com/doki23/arrow2", default-features = false, features = [
    "io_parquet",
    "compute",
    "io_parquet_compression",
    "io_ipc"
] }

[dev-dependencies]
tempfile = "3.3.0"
rand = "0.8.5"
